### ISSUE TITLE
Nazwa pliku z zrzutem ekranu

### ISSUE THREAD

**Issue by BelferWZ** [MzMix/Wolne-i-OtwarteAplikacjeDoPracy-z-Klockami#5]
Format nazwy pliku z zrzutem ekranu:
plansza-yyyy-mm-dd-hh-mm-ss

**Comment by MzMix** [comment]
👍

**Comment by MzMix** [comment]
Dodano w pociągach [✔]

**Comment by MzMix** [comment]
Dodano w wieżowcach [✔]
Dodano w pociągach[✔]
